### ISSUE TITLE
Parse whole .org file?

### ISSUE THREAD

**Issue by imalsogreg** [digitalmentat/orgmode-parse#1]
Hello. I'm interested in using this to parse an entire .org file with multiple headers. Not necessarily using any more org features than what you've already implemented (timestamps, headers, and properties). Any plans to flesh out the parser for multiple headers? Or am I overlooking a trivial way that users can do this?
Thanks!

**Comment by ixmatus** [comment]
Just saw this in my email, sorry I didn't respond! I'm going to close this ticket though since we chatted via email.
